# python/ch30/tutorial_outline.py
"""解いた AHC 問題のゆっくり風チュートリアル骨子を Markdown で生成（第30章）."""
from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any, Dict, List


def default_meta_path() -> Path:
    return Path(__file__).resolve().parents[2] / "data" / "ch30" / "ahc001_outline.json"


def load_meta(path: Path) -> Dict[str, Any]:
    with path.open(encoding="utf-8") as f:
        return json.load(f)


def bullet_lines(items: List[str], prefix: str = "- ") -> str:
    return "\n".join(f"{prefix}{x}" for x in items)


def generate_outline(meta: Dict[str, Any]) -> str:
    pid = meta.get("problem_id", "AHC???")
    title = meta.get("title", "（タイトル未設定）")
    band = meta.get("rating_band", meta.get("difficulty", "?"))
    sections: List[str] = meta.get("sections", [])
    key_ideas: List[str] = meta.get("key_ideas", [])
    pitfalls: List[str] = meta.get("pitfalls", [])
    refs: List[str] = meta.get("references", [])
    score = meta.get("solved_score", "?")
    style = meta.get("solver_style", "?")
    hours = meta.get("time_spent_hours", "?")

    section_blocks = []
    for i, sec in enumerate(sections, start=1):
        section_blocks.append(
            f"### {i}. {sec}\n\n"
            f"**霊夢**: （ここに読者の疑問）\n\n"
            f"**魔理沙**: （{sec}の解説を書く）\n"
        )

    refs_block = bullet_lines(refs) if refs else "- （公式・自分のコードへのリンク）"

    return f"""# 【ゆっくり解説骨子】{pid} {title}

> 対象: {band} / 自分の到達スコア: {score} / 方針: `{style}` / 所要: 約{hours}時間

## はじめに

**霊夢**: {pid}って、何をする問題なの？

**魔理沙**: 一言で言うと「{title}」だぜ。まずは制約とスコアの意味を押さえるんだ。

## この解説で扱うこと

{bullet_lines(key_ideas)}

## 落とし穴メモ

{bullet_lines(pitfalls)}

---

{chr(10).join(section_blocks)}
## ハンズオン（読者向け）

1. `data/ch04/sample.txt` などで入出力を確認する
2. `python/ch04/ahc001_grow.py` を動かし、スコアを出す
3. パラメータを 1 つだけ変えて差分を見る
4. タイマー付きでベストスコアを stderr に残す

## 章末まとめ（テンプレ）

> - 問題の言い換えができた
> - 貪欲/近傍のどこで効いたか言語化した
> - 次に試す改善を 1 つ書いた

## 参考リンク

{refs_block}

---
*generated by python/ch30/tutorial_outline.py*
"""


def main() -> None:
    path = Path(sys.argv[1]) if len(sys.argv) > 1 else default_meta_path()
    meta = load_meta(path)
    print(generate_outline(meta))
    print(f"outline for {meta.get('problem_id', '?')} written to stdout", file=sys.stderr)


if __name__ == "__main__":
    main()
